python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Science/final_model.pt"   --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Space/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Politics/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Military/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Religion/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Computers/final_model.pt" --output_dir "PiLM-Controller-results/outputs_seed20"
python controller_inference.py --seed 20 --sample --controller "Controllers/controller-Legal/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed20"

python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Science/final_model.pt"   --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Space/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Politics/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Military/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Religion/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Computers/final_model.pt" --output_dir "PiLM-Controller-results/outputs_seed21"
python controller_inference.py --seed 21 --sample --controller "Controllers/controller-Legal/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed21"

python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Science/final_model.pt"   --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Space/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Politics/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Military/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Religion/final_model.pt"  --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Computers/final_model.pt" --output_dir "PiLM-Controller-results/outputs_seed22"
python controller_inference.py --seed 22 --sample --controller "Controllers/controller-Legal/final_model.pt"     --output_dir "PiLM-Controller-results/outputs_seed22"